Propogating CGE predicted phenotypes from resfinder to the summaries
phac-nml/staramr pull request #173
Opened 2023-04-17 20:45 UTC by emarinier

2023-04-18 21:38 UTC, apetkau requested changes
This looks great. Thanks so much Eric 😄 .

One thing I did notice, which I think might be unrelated to this particular PR but is related to adding the **CGE Predicted Phenotype**  is that some of the values show up as "unknown" even though they appear to exist in the ResFinder database.

For example, in the attached fasta file, [GCF_000008105.1_ASM810v1_genomic.fna.zip](https://github.com/phac-nml/staramr/files/11266503/GCF_000008105.1_ASM810v1_genomic.fna.zip), I get a **unknown[cmlA1_1_M64556]** result when running staramr.

| Isolate ID | Gene | Predicted Phenotype | CGE Predicted Phenotype | %Identity | %Overlap | HSP Length/Total Length | Contig | Start | End | Accession |
|-|-|-|-|-|-|-|-|-|-|-|
GCF_000008105.1_ASM810v1_genomic | cmlA1 | chloramphenicol | **unknown[cmlA1_1_M64556]** | 99.92 | 100.00 | 1260/1260 | ref\|NC_006856.1\| | 41866 | 40607 | M64556 |

However, looking up the following accession, **M64556**, in the ResFinder database:

https://bitbucket.org/genomicepidemiology/resfinder_db/src/fa32d9a3cf0c12ec70ca4e90c45c0d590ee810bd/phenotypes.txt#lines-2297

I get a Phenotype of **Amphenicol**.

I would expect to see this same phenotype, **Amphenicol**, in the StarAMR results table instead of **unknown[cmlA1_1_M64556]**.

Would you have an idea why this is happening?

2023-05-16 22:44 UTC, apetkau requested changes
This looks great. I did a comparison of results with ~1300 campylobacter genomes and the information all seems consistent (only the **CGE Predicted Phenotype** column is added).

Just one comment.

2023-05-18 17:28 UTC, emarinier commented on staramr/tests/unit/results/test_AMRDetectionSummaryResistance.py
> +            ['file1', 'blaCTX-M-55', 'ampicillin, ceftriaxone', 'ampicillin, ceftriaxone', 99.73, 100.00,
I believe this is now addressed in [23b9bc9](https://github.com/phac-nml/staramr/pull/173/commits/23b9bc9a81733a11985cc11c8e2dd7ead38e10b5).

2023-05-18 17:28 UTC, emarinier commented
As per request, the changelog has been updated.

2023-05-26 22:09 UTC, apetkau approved these changes
Thanks so much. This all looks great to me. Merging.

2023-05-26 22:09 UTC, merged